name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for noticing an issue and informing us about that. Hope you will like our work."
        pr-message: "Thanks for contributing to our repository for the first time, we will have a look to this pull request"
